version: "3.7"
services:
  nginx:
    build:
      context: App/docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: App/docker/php-fpm
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1  remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
  mysql:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8084:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${DB_ROOT_PASSWORD}