<footer class="footer bg-dark fixed-bottom">
    <div class="footer-copyright text-center py-2 text-light">© 2020 Copyright:
        <a href="/" class="text-light"> Camagru.com</a>
    </div>
</footer>
<!--<footer class="page-footer font-small bg-dark fixed-bottom">-->
<!--    <div class="footer-copyright text-center py-3 text-light">© 2020 Copyright:-->
<!--        <a href="/" class="text-light"> Camagru.com</a>-->
<!--    </div>-->
<!--</footer>-->
</body>
</html>