<?php require_once __DIR__ . '/../layouts/header.phtml' ?>
<div class="container h-100">
    <?php if (isset($params['error'])): ?>
        <div class="alert alert-danger" role="alert">
          <strong>Ошибка:</strong>
            <?= htmlspecialchars($params['error']) ?>
            <button id="alertX" type="button" class="close">
                &times;
            </button>
        </div>
    <?php endif; ?>
    <?php if (isset($_SESSION['success'])): ?>
        <div class="alert alert-success" role="alert">
            <strong>Успех:</strong>
            <?= htmlspecialchars($_SESSION['success']) ?>
            <button id="alertX" type="button" class="close">
                &times;
            </button>
            <?php $_SESSION['success'] = null ?>
        </div>
    <?php endif; ?>
    <div class="row justify-content-lg-center justify-content-md-center justify-content-sm-center justify-content-center my-login-page">
        <div class="col-lg-4 col-md-5 col-sm-6 col-7">
            <div class="card mt-5">
                <form class="card-body" action='#' method="POST">
                    <div id="loginContainer" class="form-group">
                        <label for="login" class="">Email или логин:</label>
                        <input id="login" type="text" class="form-control" name="user[login]"
                               value="<?= htmlspecialchars($params['user']['login'] ?? '') ?>">
                    </div>

                    <div class="form-group">
                            <label for="password" class="float-left">Пароль:
                            </label>
                        <div id="passwordContainer" style="position: relative">
                            <input id="password" type="password" class="form-control" name="user[password]">
                            <a id="password-control" class="password-control"></a>
                        </div>
                    </div>
                    <br>
                    <div class="form-group m-0">
                        <button id="submit" class="btn btn-success btn-block" type="submit" name="submit">Войти</button>
                    </div>
                    <hr class="mb-4">
                    <div class="mt-4 text-center">
                        Нет аккаунта?  <a href="/auth/registration">Создать</a>
                    </div>
                    <div class="mt-4 text-center">
                        Забыли пароль? <a href="/auth/restore">Восстановить</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    <script src="../alertClose.js" type="text/javascript"></script>
    <script src="../regValidate.js" type="text/javascript"></script>
    <script src="../showPassword.js" type="text/javascript"></script>
<?php require_once __DIR__ . '/../layouts/footer.phtml' ?>