<?php require_once __DIR__ . '/../layouts/header.phtml' ?>
<?php if (isset($params['error'])): ?>
    <div class="alert alert-danger" role="alert">
        <strong>Ошибка:</strong>
        <?= htmlspecialchars($params['error']) ?>
        <button id="alertX" type="button" class="close">
            &times;
        </button>
    </div>
<?php endif; ?>

<div class="container h-100">
    <div class="row justify-content-lg-center justify-content-md-center justify-content-sm-center justify-content-center my-login-page">
        <div class="col-lg-4 col-md-5 col-sm-6 col-7">
            <div class="card mt-5">
                <form class="card-body" action='#' method="POST">
                    <div class="form-group mb-4">
                    <div id="loginContainer" class="form-group">
                        <label for="login" class="">Логин:</label>
                        <input id="login" type="text" class="form-control" name="user[login]" minlength="3"
                               value="<?= htmlspecialchars($params['user']['login'] ?? '') ?>">
                    </div>
                    </div>
                    <div class="form-group mb-4">
                        <div id="emailContainer">
                            <label for="email">Email:</label>
                            <input id="email" type="email" class="form-control" name="user[email]"
                                   value="<?= htmlspecialchars($params['user']['email'] ?? '') ?>">
                        </div>
                    </div>

                    <div class="form-group mb-4">
                        <label for="password" class="float-left">Пароль:</label>
                        <div id="passwordContainer" style="position: relative">
                            <input id="password" type="password" class="form-control" minlength="8"
                                   name="user[password]">
                            <a id="password-control" class="password-control"></a>
                        </div>
                    </div>

                    <div class="form-group mb-5">
                        <label for="confirm" class="float-left">Повторите пароль:</label>
                        <div id="confirmContainer" style="position: relative">
                            <!--                                          #TODO создать отдельный класс-->
                            <input id="confirm" type="password" class="form-control" name="user[confirm]" minlength="8">
                            <a id="confirm-control" class="password-control"></a>
                        </div>
                    </div>

                    <div class="form-group m-0">
                        <button id="submit" class="btn btn-success btn-block" type="submit" name="submit">
                            Подтвердить
                        </button>
                    </div>
                    <hr class="mb-4">
                    <div class="mt-4 text-center">
                        Уже есть аккаунт? <a href="/auth/login">Войти</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="../showPassword.js" type="text/javascript"></script>
<script src="../regValidate.js" type="text/javascript"></script>
<script src="../alertClose.js" type="text/javascript"></script>
<?php //endif;?>
<?php //if($params['flag'] === 1): ?>
<!--<div>-->
<!--	<p>Спасибо за регистрацию. Вам необходимо подтвердить ваш email. Для этого нужно перейти по ссылке которую мы отправили на ваш email</p>-->
<!--</div>-->
<?php //endif;?>
<?php require_once __DIR__ . '/../layouts/footer.phtml' ?>
