<?php require_once __DIR__ . '/../layouts/header.phtml' ?>
    <div class="container h-100">
        <?php if (isset($params['error'])): ?>
            <div class="alert alert-danger" role="alert">
                <strong>Ошибка:</strong>
                <?= htmlspecialchars($params['error']) ?>
                <button id="alertX" type="button" class="close">
                    &times;
                </button>
            </div>
        <?php endif; ?>
        <div class="row justify-content-lg-center justify-content-md-center justify-content-sm-center justify-content-center my-login-page">
            <div class="col-lg-4 col-md-5 col-sm-6 col-7">
                <div class="card mt-5">
                    <form class="card-body" action='#' method="POST">
                        <input hidden name="user[token]" value="<?= htmlspecialchars($params['user']['token'] ?? '')?>">
                        <h5 class="card-title text-center"> <strong>Смените пароль:</strong> </h5>
                        <br>
                        <div class="form-group">
                            <label for="password" class="float-left">Пароль:</label>
                            <div id="passwordContainer" style="position: relative">
                                <input id="password" type="password" class="form-control" name="user[password]">
                                <a id="password-control" class="password-control"></a>
                            </div>
                        </div>

                        <br>

                        <div class="form-group">
                            <label for="confirm" class="float-left">Повторите пароль:</label>
                            <div id="confirmContainer" style="position: relative">
                                <!--                                          #TODO создать отдельный класс-->
                                <input id="confirm" type="password" class="form-control" name="user[confirm]">
                                <a id="confirm-control" class="password-control"></a>
                            </div>
                        </div>

                        <br>

                        <div class="form-group m-0">
                            <button id="submit" class="btn btn-success btn-block" type="submit" name="submit">
                                Подтвердить
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="../regValidate.js" type="text/javascript"></script>
    <script src="../alertClose.js" type="text/javascript"></script>
    <script src="../showPassword.js" type="text/javascript"></script>
<?php require_once __DIR__ . '/../layouts/footer.phtml' ?>