<?php require_once __DIR__ . '/../layouts/header.phtml' ?>
    <div class="container h-100">
        <?php if (isset($params['error'])): ?>
            <div class="alert alert-danger" role="alert">
                <strong>Ошибка:</strong>
                <?= htmlspecialchars($params['error']) ?>
                <button id="alertX" type="button" class="close">
                    &times;
                </button>
            </div>
        <?php endif; ?>
        <div class="row justify-content-lg-center justify-content-md-center justify-content-sm-center justify-content-center my-login-page">
            <div class="col-lg-4 col-md-5 col-sm-6 col-7">
                <div class="card mt-5">
                    <form class="card-body" action='#' method="POST">
                        <h5 class="card-title text-center"> <strong>Забыли свой пароль?</strong> </h5>
                        <p class="text-center">Введите свой e-mail адрес, и мы отправим вам письмо со ссылкой для сброса пароля.
                        </p>
                        <div class="form-group">
                            <div id="emailContainer">
                                <label for="email"></label>
                                <input id="email" type="email" class="form-control" name="user[email]" placeholder="Email"
                                       value="<?= htmlspecialchars($params['user']['email'] ?? '') ?>">
                            </div>
                        </div>
                        <div class="form-group m-0">
                            <button id="submit" class="btn btn-success btn-block" type="submit" name="submit">
                                Сбросить пароль
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="../alertClose.js" type="text/javascript"></script>
    <script src="../regValidate.js" type="text/javascript"></script>
<?php require_once __DIR__ . '/../layouts/footer.phtml' ?>