<?php require_once __DIR__ . '/../layouts/header.phtml' ?>
<?php if (isset($params['error'])): ?>
    <div class="alert alert-danger" role="alert">
        <strong>Ошибка:</strong>
        <?= htmlspecialchars($params['error']) ?>
        <button id="alertX" type="button" class="close">
            &times;
        </button>
    </div>
<?php endif; ?>
<?php if (isset($params['success'])): ?>
    <div class="alert alert-success" role="alert">
        <strong>Успех:</strong>
        <?= htmlspecialchars($params['success']) ?>
        <button id="alertX" type="button" class="close">
            &times;
        </button>
    </div>
<?php endif; ?>
<div class="container my-5 pb-5">
    <h3 class="pb-3 text-center">Создать фото</h3>
    <div class="row">
        <div class="col-8">
            <div class="card shadow-sm">
                <div id="imageContainer">
                    <img id="blackBox" class="card-img-top test"  src="https://homex.ru/upload/iblock/bf5/bf5797fe08aa55ae5bfaa0b5dbfd3354.jpg" alt="picture">
                    <div id="maskContainer" style="position: relative">
                    </div>
                    <video id="video" hidden class="embed-responsive embed-responsive-1by1">
                    </video>
                </div>
                <div class="card-body">
                    <div class="input-group mb-3">
                        <input id="title" type="text" class="form-control" placeholder="Подпись">
                    </div>
                </div>
                <div class="card-footer">
                    <div id="buttonContainer" class="d-flex row">
                        <div class="col-md-6 col-xs-1 mb-3">
                            <button id="turnCamera" class="btn btn-success ">Включить камеру</button>
                        </div>
                        <div class="col-md-6 col-xs-1 mb-3">
                            <input type="file" id="uploadPhoto" name="file[]">
                        </div>
                    </div>
                    <div id="buttonContainer" class="d-flex row justify-content-center">
                        <button id="makePhoto" hidden class="btn btn-success">Сделать фото</button>
                    </div>
                    <div id="buttonContainer" class="d-flex row justify-content-center">
                        <button id="savePhoto" hidden class="btn btn-success">Сохранить</button>
                    </div>
                </div>
            </div>
        </div>
        <div id="masks_row" class="col-4 row" hidden>
            <?php for ($i = 1; $i <= 12; $i++): ?>
                <div class="col-md-4 col-sm-4 col-lg-4 thumb">
                    <label for="mask_id_<?php echo $i; ?>">
                        <input type="checkbox" class="checkbox" value="../<?= $i; ?>.png" id="mask_id_<?= $i; ?>"
                               onchange="createMask('mask_id_<?= $i; ?>')">
                        <img class="img-fluid" src="../<?= $i; ?>.png" alt=""/>
                </div>
            <?php endfor; ?>
        </div>

    </div>

    <div id="galleryContainer" class="row">
    </div>

</div>

<script src="../capture.js" type="text/javascript"></script>
    <script src="../alertClose.js" type="text/javascript"></script>
<?php require_once __DIR__ . '/../layouts/footer.phtml' ?>