<?php require_once __DIR__ . '/../layouts/header.phtml'?>
    <div class="container">
        <?php if (isset($params['error'])): ?>
            <div class="alert alert-danger" role="alert">
                <strong>Ошибка:</strong>
                <?= htmlspecialchars($params['error']) ?>
                <button id="alertX" type="button" class="close">
                    &times;
                </button>
            </div>
        <?php endif; ?>
        <?php if (isset($params['success'])): ?>
            <div class="alert alert-success" role="alert">
                <strong>Успех:</strong>
                <?= htmlspecialchars($params['success']) ?>
                <button id="alertX" type="button" class="close">
                    &times;
                </button>
            </div>
        <?php endif; ?>
        <div class="py-5 text-center">
            <h2>Настройки</h2>
        </div>
        <div class="row">
            <div class="col-md-4 order-md-1 mb-1">
                <div class="list-group">
                    <a href="/setting/email" class="list-group-item list-group-item-action">
                        Сменить email
                    </a>
                    <a href="/setting/login" class="list-group-item list-group-item-action active">Сменить логин</a>
                    <a href="/setting/password" class="list-group-item list-group-item-action">Сменить пароль</a>
                    <a href="/setting/notify" class="list-group-item list-group-item-action">
                        Уведомления
                    </a>
                </div>
            </div>
            <div class="col-md-5 order-md-2">
                <!--            <h4 class="mb-3">Billing address</h4>-->
                <form action="#" method="POST">

                    <div id="loginContainer" class="mb-3">
                        <label for="login">Логин:</label>
                        <input type="text" class="form-control" id="login" name="user[login]" value="<?= htmlspecialchars($params['login'] ?? '') ?>">
                    </div>

                    <hr class="mb-4">
                    <button id="submit" class="btn btn-success btn-block" type="submit">Подтвердить</button>
                </form>
            </div>
        </div>
    </div>
    <script src="../alertClose.js" type="text/javascript"></script>
    <script src="../regValidate.js" type="text/javascript"></script>
<?php require_once __DIR__ . '/../layouts/footer.phtml'?>