<?php require_once __DIR__ . '/layouts/header.phtml' ?>

    <div class="container py-5">
        <div class="row">
            <?php foreach ($params['gallery'] as $value): ?>
                <div class="col-md-4 col-sm-4 col-lg-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-header">
                            <p class="card-text"><?= htmlspecialchars($value['login'])?></p>
                        </div>
                        <a href="/photo/<?= htmlspecialchars($value['id'])?>" target="_self" data-size="1600x1067">
                            <img alt="picture"
                                 src="<?= $value['photo'] ?>"
                                 class="img-fluid"/>
                        </a>
                        <div class="card-body">
                            <hr class="mb-3">
                            <p class="card-text"><?= htmlspecialchars($value['title']) ?></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted"><?= htmlspecialchars($value['created_at']) ?></small>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php if ($params['count_pages'] > 1): ?>
            <nav aria-label="Page navigation example ">
                <ul class="pagination justify-content-center">
                    <?php if ($params['page'] > 1): ?>
                        <li class="page-item">
                            <a class="page-link" aria-label="Previous"
                               href="/?page=<?= $params['page'] > 2 ? $params['page'] - 1 : 1 ?>">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php for ($i = 1; $i <= $params['count_pages']; $i++): ?>
                        <li class="page-item"><a class="page-link"
                                                 href="/?page=<?= $i ?>"><?= $i ?></a>
                        </li>
                    <?php endfor; ?>
                    <?php if ($params['page'] < $params['count_pages']): ?>
                        <li class="page-item">
                            <a class="page-link" aria-label="Next"
                               href="/?page=<?= $params['page'] + 1 ?>">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span></a>
                        </li>
                    <?php endif; ?>
                </ul>
            </nav>
        <?php endif; ?>
    </div>
<?php require_once __DIR__ . '/layouts/footer.phtml' ?>